package lesson21;

import lesson18.serialization.Parrot;

import java.io.File;

/**
 * This class allows to show full content of a directory including a content of inner directories.
 * Two methods
 * One class variables
 *
 * @author YehKhUni
 * @version 1.0
 */
public class DirContentJavadoc {
    /**
     * This is a single nonsense variable of this class.
     * It is there only to test a documentation generated by javadoc.
     */
    private Parrot kesha;

    /**
     * This is a setter for nonsense kesha.
     */
    public void setKesha(Parrot kesha) {
        this.kesha = kesha;
    }

    /**
     * The main method
     *
     * @param args
     */
    public static void main(String[] args) {
        File myDir = new File("src");
        showContent(myDir);
    }

    /**
     * This is a static void methods. It takes a File-object as its input.
     * If input object isn't a directory it will output something like an exception.
     *
     * @param dir
     */
    public static void showContent(File dir) {
        if (dir.isDirectory()) {
            for (String file : dir.list()) {
                File innerFile = new File(dir.getPath() + "\\" + file);
                if (innerFile.isDirectory()) {
                    System.out.println('\n' + file + '\n');
                    showContent(innerFile);
                } else {
                    System.out.println("    " + file);
                }
            }
        } else {
            System.out.println("This is not a directory!");
        }
    }
}
